/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package segurodevida;

import javax.swing.JOptionPane;

/**
 *
 * @author CBN
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    SeguroDeVida calcularSeguro = new SeguroDeVida();
    boolean siFumador=false,siAlcoholico=false,siDrogadicto=false,siCardiaco=false;
    long valorBase=0;
    public Formulario() {
        initComponents();
        txtvalorbase.setText("");
        lbresultado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgFumador = new javax.swing.ButtonGroup();
        rgAlcoholico = new javax.swing.ButtonGroup();
        rgSustancias = new javax.swing.ButtonGroup();
        rgCardiacos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtvalorbase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbfumadorsi = new javax.swing.JRadioButton();
        rbfumadorno = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbalcoholicosi = new javax.swing.JRadioButton();
        rbalcoholicono = new javax.swing.JRadioButton();
        rbsustanciassi = new javax.swing.JRadioButton();
        rbsustanciasno = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbcardiacosi = new javax.swing.JRadioButton();
        rbcardiacono = new javax.swing.JRadioButton();
        chbaceptar = new javax.swing.JCheckBox();
        btncalcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lbresultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese el valor base");

        txtvalorbase.setText("jTextField1");

        jLabel2.setText("Es usted alcoholico?");

        rgFumador.add(rbfumadorsi);
        rbfumadorsi.setText("SI");

        rgFumador.add(rbfumadorno);
        rbfumadorno.setText("No");

        jLabel3.setText("Es usted alcoholico?");

        rgAlcoholico.add(rbalcoholicosi);
        rbalcoholicosi.setText("SI");
        rbalcoholicosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbalcoholicosiActionPerformed(evt);
            }
        });

        rgAlcoholico.add(rbalcoholicono);
        rbalcoholicono.setText("No");

        rgSustancias.add(rbsustanciassi);
        rbsustanciassi.setText("SI");

        rgSustancias.add(rbsustanciasno);
        rbsustanciasno.setText("No");

        jLabel4.setText("Consume sustancias alcogenas?");

        jLabel5.setText("Es usted fumador activo?");

        jLabel6.setText("Tiene antecedentes cardiacos?");

        rgCardiacos.add(rbcardiacosi);
        rbcardiacosi.setText("SI");

        rgCardiacos.add(rbcardiacono);
        rbcardiacono.setText("No");

        chbaceptar.setText("Acepto los terminos y condiciones");
        chbaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbaceptarActionPerformed(evt);
            }
        });

        btncalcular.setText("Calcular seguro de vida");
        btncalcular.setEnabled(false);
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        lbresultado.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbfumadorno)
                                    .addComponent(rbfumadorsi))
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(txtvalorbase, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbalcoholicono)
                                            .addComponent(rbalcoholicosi))))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbsustanciasno)
                                            .addComponent(rbsustanciassi))
                                        .addGap(87, 87, 87))))))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbcardiacono)
                            .addComponent(rbcardiacosi)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbaceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbresultado)
                        .addGap(475, 475, 475))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalorbase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbfumadorsi)
                        .addGap(18, 18, 18)
                        .addComponent(rbfumadorno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbsustanciassi)
                        .addGap(18, 18, 18)
                        .addComponent(rbsustanciasno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbalcoholicosi)
                        .addGap(18, 18, 18)
                        .addComponent(rbalcoholicono)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbcardiacosi)
                        .addGap(18, 18, 18)
                        .addComponent(rbcardiacono)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbaceptar)
                            .addComponent(btncalcular))
                        .addGap(18, 18, 18)
                        .addComponent(lbresultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbalcoholicosiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbalcoholicosiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbalcoholicosiActionPerformed

    private void chbaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbaceptarActionPerformed
        if(chbaceptar.isSelected()){
            btncalcular.setEnabled(true);
        }else{
            btncalcular.setEnabled(false);
        }
            
        
    }//GEN-LAST:event_chbaceptarActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        try{
            calcularSeguro();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Faltan campos por diligenciar ", "Error ", JOptionPane.ERROR_MESSAGE);
        }     
    }//GEN-LAST:event_btncalcularActionPerformed
    private void calcularSeguro(){
        valorBase = Long.parseLong(txtvalorbase.getText());
        if(rbfumadorsi.isSelected()){
            siFumador= true;
        }else{
            siFumador=false;
        }
        if(rbalcoholicosi.isSelected()){
            siAlcoholico=true;
        }else{
            siAlcoholico=false;
        }
        if(rbsustanciassi.isSelected()){
            siDrogadicto= true;
        }else{
            siDrogadicto=false;
        }
        if(rbcardiacosi.isSelected()){
            siCardiaco=true;
        }else{
            siCardiaco=false;
        }
        lbresultado.setText(Long.toString(calcularSeguro.Calcular(valorBase,siFumador,siAlcoholico,siDrogadicto,siCardiaco)));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JCheckBox chbaceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbresultado;
    private javax.swing.JRadioButton rbalcoholicono;
    private javax.swing.JRadioButton rbalcoholicosi;
    private javax.swing.JRadioButton rbcardiacono;
    private javax.swing.JRadioButton rbcardiacosi;
    private javax.swing.JRadioButton rbfumadorno;
    private javax.swing.JRadioButton rbfumadorsi;
    private javax.swing.JRadioButton rbsustanciasno;
    private javax.swing.JRadioButton rbsustanciassi;
    private javax.swing.ButtonGroup rgAlcoholico;
    private javax.swing.ButtonGroup rgCardiacos;
    private javax.swing.ButtonGroup rgFumador;
    private javax.swing.ButtonGroup rgSustancias;
    private javax.swing.JTextField txtvalorbase;
    // End of variables declaration//GEN-END:variables
}
